--- 
title: "NYC - Motor Vehicle Collisions"
author: "Akshay Pakhle, Harguna Sood, Karthik Rajaraman"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The latest census data [(Public Use Microdata Sample)](https://www.census.gov/programs-surveys/acs/data/pums.html) shows that about 45 percent of the 3.1 million households own a car. So, it comes as no surprise that annual average(2012-2019) of motor vehicle collision(MVC) is north of 10,000. With about 1000 losing their lives and several thousands being hospitalized every year owing to such incidents. The city administration has taken several steps to curb MVCs after it reached an all time high of 149,218 crashes in 2015.

Our analysis focuses on the impact of the Vision Zero program introduced by Mayor of New York, Bill de Blasio , in 2014. We analyse the overall trends in vehicular collision in the state of New York. By measuring the effect of policies made by the city's administration, we aim to provide insights to substantiate future policy updates. 

This analysis investigates:
- Most frequent causes of accidents
- Vehicle type involved in most crashes
- Intersections that are most vulnerable to crashes
- Increase in severity of crashes

We have also created an interactive plot that helps in quick exploration of the distribution of crashes over time.

